# Generated by Django 2.0.3 on 2018-03-27 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_timestamp', models.DateTimeField()),
                ('soil_temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('air_temp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('soil_moisture', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'garden_data',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'weather_station',
            },
        ),
        migrations.AddIndex(
            model_name='weatherstation',
            index=models.Index(fields=['weather_station'], name='weather_sta_weather_efbae9_idx'),
        ),
        migrations.AddField(
            model_name='gardendata',
            name='weather_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_station_id', to='garden_data.WeatherStation'),
        ),
        migrations.AddIndex(
            model_name='gardendata',
            index=models.Index(fields=['weather_station', 'observation_timestamp'], name='garden_data_weather_f55fd1_idx'),
        ),
    ]
